#version 450
#extension GL_EXT_buffer_reference : require

layout(local_size_x = 3, local_size_y = 1, local_size_z = 1) in;

layout(buffer_reference) buffer VertexDataPtr {
    vec4 positions[3];
};

layout(push_constant) uniform PushConstants {
    VertexDataPtr srcBuffer;
    VertexDataPtr dstBuffer;
};

const vec2 imageSize = vec2(800, 600);

void main() {
    uint idx = gl_GlobalInvocationID.x;
    dstBuffer.positions[idx] = srcBuffer.positions[idx] + vec4(0.001, 0.001, 0.00, 0.00);
}
