#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
// gl_GlobalInvocationID

layout(set = 0, binding = 0) uniform Input {
    vec4 positions[3];
} srcBuffer;

layout(set = 0, binding = 1) writeonly buffer Output {
    vec4 positions[3];
} dstBuffer;

void main() {
    for (uint idx = 0; idx < 3; idx++) {
        dstBuffer.positions[idx] = srcBuffer.positions[idx] + vec4(0.01, 0.01, 0.01, 0.01);
    }
}
